# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commdef.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commdef.proto',
  package='commdef',
  serialized_pb='\n\rcommdef.proto\x12\x07\x63ommdef*\x1f\n\x07SexType\x12\n\n\x06\x66\x65male\x10\x00\x12\x08\n\x04male\x10\x01*E\n\x0fLeaderboardType\x12\x0e\n\nnone_board\x10\x00\x12\x10\n\x0c\x62\x61ttle_power\x10\x01\x12\x10\n\x0cregion_level\x10\x02*%\n\rSkillTrigType\x12\x08\n\x04\x62uff\x10\x00\x12\n\n\x06\x64\x65\x62uff\x10\x01*l\n\tSkillType\x12\x08\n\x04none\x10\x00\x12\t\n\x05sword\x10\x01\x12\x08\n\x04\x66ist\x10\x02\x12\t\n\x05knife\x10\x03\x12\n\n\x06talent\x10\n\x12\x07\n\x03pet\x10\x0b\x12\x07\n\x03QTE\x10\x0c\x12\x0b\n\x07zhengwu\x10\r\x12\n\n\x06moster\x10\x0e*;\n\x0fSkillTargetType\x12\t\n\x05\x65nemy\x10\x00\x12\x08\n\x04self\x10\x01\x12\x13\n\x0fselfAndTeammate\x10\x02*[\n\tSkillSlot\x12\r\n\tnoramlAtk\x10\x00\x12\n\n\x06skill1\x10\x01\x12\n\n\x06skill2\x10\x02\x12\n\n\x06skill3\x10\x03\x12\n\n\x06weapon\x10\x04\x12\x0f\n\x0bzhengwuslot\x10\x05*<\n\x05Rules\x12\x1a\n\x16Limitation_PlayerLevel\x10\x00\x12\x17\n\x13Limitation_ColdDown\x10\x01')

_SEXTYPE = _descriptor.EnumDescriptor(
  name='SexType',
  full_name='commdef.SexType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='female', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='male', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=57,
)

SexType = enum_type_wrapper.EnumTypeWrapper(_SEXTYPE)
_LEADERBOARDTYPE = _descriptor.EnumDescriptor(
  name='LeaderboardType',
  full_name='commdef.LeaderboardType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none_board', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='battle_power', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='region_level', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=59,
  serialized_end=128,
)

LeaderboardType = enum_type_wrapper.EnumTypeWrapper(_LEADERBOARDTYPE)
_SKILLTRIGTYPE = _descriptor.EnumDescriptor(
  name='SkillTrigType',
  full_name='commdef.SkillTrigType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='buff', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='debuff', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=130,
  serialized_end=167,
)

SkillTrigType = enum_type_wrapper.EnumTypeWrapper(_SKILLTRIGTYPE)
_SKILLTYPE = _descriptor.EnumDescriptor(
  name='SkillType',
  full_name='commdef.SkillType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sword', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fist', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='knife', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='talent', index=4, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pet', index=5, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QTE', index=6, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='zhengwu', index=7, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='moster', index=8, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=169,
  serialized_end=277,
)

SkillType = enum_type_wrapper.EnumTypeWrapper(_SKILLTYPE)
_SKILLTARGETTYPE = _descriptor.EnumDescriptor(
  name='SkillTargetType',
  full_name='commdef.SkillTargetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='enemy', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='self', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='selfAndTeammate', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=279,
  serialized_end=338,
)

SkillTargetType = enum_type_wrapper.EnumTypeWrapper(_SKILLTARGETTYPE)
_SKILLSLOT = _descriptor.EnumDescriptor(
  name='SkillSlot',
  full_name='commdef.SkillSlot',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='noramlAtk', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='skill1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='skill2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='skill3', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='weapon', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='zhengwuslot', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=340,
  serialized_end=431,
)

SkillSlot = enum_type_wrapper.EnumTypeWrapper(_SKILLSLOT)
_RULES = _descriptor.EnumDescriptor(
  name='Rules',
  full_name='commdef.Rules',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Limitation_PlayerLevel', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Limitation_ColdDown', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=433,
  serialized_end=493,
)

Rules = enum_type_wrapper.EnumTypeWrapper(_RULES)
female = 0
male = 1
none_board = 0
battle_power = 1
region_level = 2
buff = 0
debuff = 1
none = 0
sword = 1
fist = 2
knife = 3
talent = 10
pet = 11
QTE = 12
zhengwu = 13
moster = 14
enemy = 0
self = 1
selfAndTeammate = 2
noramlAtk = 0
skill1 = 1
skill2 = 2
skill3 = 3
weapon = 4
zhengwuslot = 5
Limitation_PlayerLevel = 0
Limitation_ColdDown = 1




# @@protoc_insertion_point(module_scope)
