# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UIFrame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UIFrame.proto',
  package='dbc',
  serialized_pb='\n\rUIFrame.proto\x12\x03\x64\x62\x63\":\n\x0cUIFrameTable\x12\r\n\x05tname\x18\x01 \x01(\t\x12\x1b\n\x05tlist\x18\x02 \x03(\x0b\x32\x0c.dbc.UIFrame\"\x84\x01\n\x07UIFrame\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x10\n\x08WindowID\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x11\n\tFrameType\x18\x04 \x01(\x05\x12\x12\n\nBarContent\x18\x05 \x01(\t\x12\x11\n\tJumpWndID\x18\x06 \x01(\t\x12\x13\n\x0bJumpWndType\x18\x07 \x01(\t')




_UIFRAMETABLE = _descriptor.Descriptor(
  name='UIFrameTable',
  full_name='dbc.UIFrameTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tname', full_name='dbc.UIFrameTable.tname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tlist', full_name='dbc.UIFrameTable.tlist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=80,
)


_UIFRAME = _descriptor.Descriptor(
  name='UIFrame',
  full_name='dbc.UIFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dbc.UIFrame.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WindowID', full_name='dbc.UIFrame.WindowID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='dbc.UIFrame.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FrameType', full_name='dbc.UIFrame.FrameType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BarContent', full_name='dbc.UIFrame.BarContent', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='JumpWndID', full_name='dbc.UIFrame.JumpWndID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='JumpWndType', full_name='dbc.UIFrame.JumpWndType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=83,
  serialized_end=215,
)

_UIFRAMETABLE.fields_by_name['tlist'].message_type = _UIFRAME
DESCRIPTOR.message_types_by_name['UIFrameTable'] = _UIFRAMETABLE
DESCRIPTOR.message_types_by_name['UIFrame'] = _UIFRAME

class UIFrameTable(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UIFRAMETABLE

  # @@protoc_insertion_point(class_scope:dbc.UIFrameTable)

class UIFrame(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UIFRAME

  # @@protoc_insertion_point(class_scope:dbc.UIFrame)


# @@protoc_insertion_point(module_scope)
