//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/Section.proto
namespace dbc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SectionTable")]
  public partial class SectionTable : global::ProtoBuf.IExtensible
  {
    public SectionTable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<dbc.Section> _tlist = new global::System.Collections.Generic.List<dbc.Section>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dbc.Section> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Section")]
  public partial class Section : global::ProtoBuf.IExtensible
  {
    public Section() {}
    
    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _UnLock = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"UnLock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UnLock
    {
      get { return _UnLock; }
      set { _UnLock = value; }
    }
    private string _PreSection = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PreSection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PreSection
    {
      get { return _PreSection; }
      set { _PreSection = value; }
    }
    private int _Map = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Map", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Map
    {
      get { return _Map; }
      set { _Map = value; }
    }
    private int _Exp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private int _Potential = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Potential", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Potential
    {
      get { return _Potential; }
      set { _Potential = value; }
    }
    private string _SpellLearning = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"SpellLearning", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SpellLearning
    {
      get { return _SpellLearning; }
      set { _SpellLearning = value; }
    }
    private int _Stength = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Stength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Stength
    {
      get { return _Stength; }
      set { _Stength = value; }
    }
    private int _Lv = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }
    private string _MonsterPool = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"MonsterPool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MonsterPool
    {
      get { return _MonsterPool; }
      set { _MonsterPool = value; }
    }
    private string _dialog = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"dialog", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dialog
    {
      get { return _dialog; }
      set { _dialog = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}