//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/Spell.proto
namespace dbc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpellTable")]
  public partial class SpellTable : global::ProtoBuf.IExtensible
  {
    public SpellTable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<dbc.Spell> _tlist = new global::System.Collections.Generic.List<dbc.Spell>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dbc.Spell> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Spell")]
  public partial class Spell : global::ProtoBuf.IExtensible
  {
    public Spell() {}
    
    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _Star = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Star
    {
      get { return _Star; }
      set { _Star = value; }
    }
    private int _DmgRate = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DmgRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DmgRate
    {
      get { return _DmgRate; }
      set { _DmgRate = value; }
    }
    private int _Damage = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Damage
    {
      get { return _Damage; }
      set { _Damage = value; }
    }
    private int _Hit = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Hit
    {
      get { return _Hit; }
      set { _Hit = value; }
    }
    private int _Block = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Block
    {
      get { return _Block; }
      set { _Block = value; }
    }
    private int _Dodge = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Dodge
    {
      get { return _Dodge; }
      set { _Dodge = value; }
    }
    private string _SkillText1 = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"SkillText1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkillText1
    {
      get { return _SkillText1; }
      set { _SkillText1 = value; }
    }
    private string _SkillText2 = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"SkillText2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkillText2
    {
      get { return _SkillText2; }
      set { _SkillText2 = value; }
    }
    private string _SkillText3 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"SkillText3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkillText3
    {
      get { return _SkillText3; }
      set { _SkillText3 = value; }
    }
    private string _SkillText4 = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"SkillText4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkillText4
    {
      get { return _SkillText4; }
      set { _SkillText4 = value; }
    }
    private string _SkillName = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"SkillName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkillName
    {
      get { return _SkillName; }
      set { _SkillName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}